### ISSUE TITLE
How could you convert Widget to pw.Widget?

### ISSUE THREAD

**Issue by mozartee** [alihassan143/htmltopdfwidgets#1]

**Comment by alihassan143** [comment]
```
 final newpdf = pw.Document();
    List<pw.Widget> widgets = await HTMLToNodesConverter(htmlText).toNodes();
```
the converter provider you the pdf provided widgets than you can use these widgets to create pdf documents

**Comment by alihassan143** [comment]
@mozartee  i am closing this issue

**Comment by leventkantaroglu** [comment]
I suggest to update readme of package. It could have supported tags

**Comment by alihassan143** [comment]
@leventkantaroglu  ok i will update the readme
