### ISSUE TITLE
font isn't work?

### ISSUE THREAD

**Issue by xiaodusx1** [alihassan143/htmltopdfwidgets#10]
bug:Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management.
but use pdf can work fine:
     final Uint8List fontData = File('assets/kaiti.ttf').readAsBytesSync();//await rootBundle.load("assets/kaiti.ttf");
  final ttf = pw.Font.ttf(fontData.buffer.asByteData());
  final pdf = pw.Document();
  var filePath = 'assets/example.pdf';
  var file = File(filePath);
  pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (pw.Context context) {
        return pw.Center(
          child: pw.Text('''<h2>welcome to beijing</h2><p>亚硝酸盐</p><p></p><p></p><p></p><p></p><p></p><p></p>''', style: pw.TextStyle(font: ttf, fontSize: 40)),
        ); // Center
      })); // Page
  await file.writeAsBytes(await pdf.save());

use htmltopdfwidgets:
var filePath = 'assets/exampleH.pdf';
  var file = File(filePath);
  final newpdf = Document();
  final html = '''<h2>welcome to beijing</h2><p>亚硝酸盐</p><p></p><p></p><p></p><p></p><p></p><p></p>''';
  final Uint8List fontData = File('assets/kaiti.ttf').readAsBytesSync();//await rootBundle.load("assets/kaiti.ttf");
  final ttf = pw.Font.ttf(fontData.buffer.asByteData());
  var widgets = await HTMLToPdf().convert(html,defaultFont: ttf);
  newpdf.addPage(MultiPage(
      maxPages: 200,
      build: (context) {
        return widgets;
      }));
  await file.writeAsBytes(await newpdf.save());

isn't work:Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management

**Comment by alihassan143** [comment]
@xiaodusx1  you need to add custom fonts in the method 
currently this package didn't suppot chinese japnese and korean language font by default but you can add your custom font in the app just provide fallback font it will works perfectly

**Comment by xiaodusx1** [comment]
> @xiaodusx1 you need to add custom fonts in the method currently this package didn't suppot chinese japnese and korean language font by default but you can add your custom font in the app just provide fallback font it will works perfectly

ok,It work.
