### ISSUE TITLE
bug:Exception: Widget won't fit into the page as its height (533.1200000000001) exceed a page height (481.88976377952747). You probably need a SpanningWidget or use a single page layout

### ISSUE THREAD

**Issue by xiaodusx1** [alihassan143/htmltopdfwidgets#11]
Exception: Widget won't fit into the page as its height (533.1200000000001) exceed a page height (481.88976377952747). You probably need a SpanningWidget or use a single page layout.
can't save pdf file.
I see pdf plugin also have so many proplem like this.if syncfusion_flutter_pdf: ^22.2.11 is better than pdf: ^3.10.4 ?

**Comment by alihassan143** [comment]
syncfusion is much harder to work with so i used pdf 
but i am planning to support the syncfusion compilation to 
Currently  pdf wont create the file if its single widget height is bigger than page height

**Comment by xiaodusx1** [comment]
> syncfusion is much harder to work with so i used pdf but i am planning to support the syncfusion compilation to Currently pdf wont create the file if its single widget height is bigger than page height

can do something to set our widget height smaller or equal than page height。

**Comment by alihassan143** [comment]
currently not its depends on html document if the paragraph and list are samller that will fit in single page than with would create document without any issue

**Comment by alihassan143** [comment]
or conditionally you can set custom height of page in Multipage layout in pdf

**Comment by xiaodusx1** [comment]
thank you .I'll give it a try, but it always gives off an unstable feeling，and not suitable for production environments.
