### ISSUE TITLE
Can't manage to render colors

### ISSUE THREAD

**Issue by Rodsevich** [alihassan143/htmltopdfwidgets#18]
Hi! I am not able to render any color on the PDF:
HTML:  
```
<span id="rojo" style="color: #F00;">rojo</span>
<span style="color: green;">verde</span>
<span class="azul" style="color: rgba(0, 0, 255, 255);">azul</span>
<b>bold</b>
<i>italica</i>
```
Code:  
```dart
final widgets = await HTMLToPdf().convert(
    rendered,
    tagStyle: HtmlTagStyle(
      italicStyle: TextStyle(
        fontStyle: FontStyle.italic,
        color: PdfColors.pink,
        fontSize: 80,
      ),
    ),
);
```

Final output:
![image](https://github.com/alihassan143/htmltopdfwidgets/assets/1907844/5aefb663-cc93-482c-aab7-fda73c852614)

**Comment by alihassan143** [comment]
![Screenshot 2024-01-06 at 3 56 49 PM](https://github.com/alihassan143/htmltopdfwidgets/assets/71745182/f402cfbf-4fcf-4f1a-b34f-422f3a20ab85)
issue fixed only rba and hex color currently supported
