### ISSUE TITLE
Unknown node type: <html br> (Package unable to parse html content)

### ISSUE THREAD

**Issue by Frankdroid7** [alihassan143/htmltopdfwidgets#20]
I keep getting this error when I call `HTMLToPdf().convert(htmlContent)`

<img width="918" alt="Screenshot 2024-01-16 at 21 00 42" src="https://github.com/alihassan143/htmltopdfwidgets/assets/30746679/3c04f3b1-879f-418e-8491-d5617875368c">

The error points to `line 392` here

<img width="828" alt="Screenshot 2024-01-16 at 21 06 23" src="https://github.com/alihassan143/htmltopdfwidgets/assets/30746679/c9d99771-15f4-432a-a6d1-146f58bbc9cf">

**Comment by alihassan143** [comment]
@Frankdroid7 can you share your html sample? you can clearly see that html is not correct their is some issue with html tags 
<html br> is not a proper tag

**Comment by Frankdroid7** [comment]
hm weird stuff, there is no <html br> in my Html content.

To test the issue, I added <html br> to the code sample you uploaded to pub.dev and it still worked.

![Uploading Screenshot 2024-01-17 at 07.59.41.png…]()
This code worked fine even with the <html br> tag

**Comment by alihassan143** [comment]
can you share you html sample so it will be easy to debug

**Comment by Frankdroid7** [comment]
Here it is:

`final htmlContent = '''
  <h1>Heading Example</h1>
  <p>This is a paragraph.</p>
  <img src="image.jpg" alt="Example Image" />
  <blockquote>This is a quote.</blockquote>
  <table>
  <tbody>
  <tr>
  <td>Okay <br /></td>
  </tr>
  </tbody>
  </table>
  <ul>
    <li>First item</li>
    <li>Second item</li>
    <li>Third item</li>
  </ul>
''';`

Thanks

**Comment by Frankdroid7** [comment]
Any update please

**Comment by alihassan143** [comment]
@Frankdroid7  currently i am busy in other things i will update you when i am free and found any bug

**Comment by Frankdroid7** [comment]
Alright thanks

> Here it is:
> 
> https://gist.github.com/Frankdroid7/f36bfcd7b52e45e6b94ea27133f416fd
> 
> Thanks

**Comment by alihassan143** [comment]
@Frankdroid7  fixed
