### ISSUE TITLE
[FR] Checkbox support

### ISSUE THREAD

**Issue by rileyhawk1417** [alihassan143/htmltopdfwidgets#25]
Can there please be support for checkboxes.

**Comment by alihassan143** [comment]
@rileyhawk1417  i will add that in upcoming release currently i am busy in some personal work you just need to check the <input> tag and find by type if you know how to do that you can create an pr otherwise I will do that when I am free

**Comment by rileyhawk1417** [comment]
Just opened an issue to track it. Although I am trying to use it for AppFlowy Editor and add [pdf support](https://github.com/AppFlowy-IO/appflowy-editor/pull/695).

**Comment by rileyhawk1417** [comment]
Am actually working on it. Though still need to figure out the nested lists part, although when its done will open up a PR so you can check it. :)

**Comment by alihassan143** [comment]
added in latest version of package

**Comment by alihassan143** [comment]
added in latest version of package
