### ISSUE TITLE
add feature

### ISSUE THREAD

**Issue by RamiHI** [alihassan143/htmltopdfwidgets#4]
Thanks for this great package

Can you add the ability to assign a bold font?

**Comment by alihassan143** [comment]
can you provide more context on that feature

**Comment by RamiHI** [comment]
like this :
![photo_2023-06-27_17-04-28](https://github.com/alihassan143/htmltopdfwidgets/assets/107990736/62bed241-1275-4a6b-a6db-fdefb41b363d)

**Comment by alihassan143** [comment]
@RamiHI  customizations added in new version
