### ISSUE TITLE
any hopes for a convertSync function?

### ISSUE THREAD

**Issue by saif-ellafi** [alihassan143/htmltopdfwidgets#40]
Thanks for this awesome initiative, I was wondering if it were ever be possible to convert the contents in sync? 
The future is giving me troubles in my map functions and other nested logic.

Cheers!

**Comment by saif-ellafi** [comment]
per what I could see, most of the async functionality comes from the fact of resolving fonts from assets. If we could give in our own Font instances perhaps...?

**Comment by alihassan143** [comment]
we can do that but without future  plugin cannot support network images
