### ISSUE TITLE
Package is switching lines

### ISSUE THREAD

**Issue by Wassiem-Ibr** [alihassan143/htmltopdfwidgets#5]
Hello

I have been using this package to write lengthy paragraphs, so now while testing my app for production I cam across this issue, I tried to solve it but I couldn't from my side.

The issue is that when you enter a paragraph, and then press enter to add another line, and then you delete the new add line, and then generate the pdf file. the package will switch between the two lines and put the bottom one on top.

please check the attached photos to see an illustraion.
![photo_2023-06-27_14-57-02](https://github.com/alihassan143/htmltopdfwidgets/assets/107564102/50c79412-806d-47b4-9f96-755b482f25c5)

![photo_2023-06-27_15-05-13](https://github.com/alihassan143/htmltopdfwidgets/assets/107564102/3da7779b-5f44-4e31-b2ed-432053e59718)

even though I am giving the text to the package in the correct way.

Please can you assist to fix this issue?

**Comment by Wassiem-Ibr** [comment]
```html
<br>Siincerely,</p><p>Noah B</p>
```

**Comment by alihassan143** [comment]
> ```
> <br>Siincerely,</p><p>Noah B</p>
> ```

@Wassiem-Ibr  their is issue in the html their isno  opening tag but their is closing tag </p> you need to provide the correct tags
currently supported tag are
p
img
list
bullet list
code
heading
