### ISSUE TITLE
<br> and <u> not working

### ISSUE THREAD

**Issue by Albert-Jan** [alihassan143/htmltopdfwidgets#7]
I've tried to export the following html, but it seems like the <br/> tag is not working.

`<p><strong>Bold text</strong></p><p>Partially <strong>bold</strong><br><em>Italic text</em><br/><u>Underlined text</u><br/>Test</p>`

It outputs as:
![Screenshot 2023-08-10 at 23 46 18](https://github.com/alihassan143/htmltopdfwidgets/assets/11318861/a8972a0a-162f-4411-a7f0-b84e25cc6ae4)

**Comment by alihassan143** [comment]
@Albert-Jan  i will update the package to support br tag
underline is issue in pdf package when the package author fix the issue i will update the package

**Comment by uragecz** [comment]
When will be release BR tag support ??? It's kinda critical for our project @alihassan143

**Comment by alihassan143** [comment]
@uragecz i am currently busy in other things i will update ASAP when i will be free
or you can add PR i will review and update the version

**Comment by alihassan143** [comment]
@uragecz issue is fixed in latest version
