### ISSUE TITLE
Working with tables

### ISSUE THREAD

**Issue by CyperDem0n** [alihassan143/htmltopdfwidgets#8]
the package isn't recognizing some essential tags like < table > and its components & < center >

**Comment by CyperDem0n** [comment]
just found out 
///
/// Supported partial rendering types:
///   bold, italic,
///   underline, strikethrough,
///   color, font,
///   href
///
/// Supported global rendering types:
///   heading: h1, h2, h3, h4, h5, h6, ...
///   block quote,
///   list: ordered list, bulleted list,
///   code block
/// 
surfing its code
great job nevertheless, hope to see it supporting what i meantioned soon
best regards

**Comment by alihassan143** [comment]
@CyperDem0n  i am almost done with the table tag it will be available in the next release

**Comment by CyperDem0n** [comment]
> @CyperDem0n i am almost done with the table tag it will be available in the next release

looking forward to it, **godspeed** you brother 🙏
